---
# TODO https://issues.redhat.com/browse/CRW-1580 update to xp3 after Aug 5
displayName: Java with JBoss EAP XP 2.0 Bootable Jar
description: Java stack with OpenJDK 11, Maven 3.6.3 and JBoss EAP XP 2.0 Bootable Jar
tags: ["Java", "OpenJDK", "Maven", "EAP", "Microprofile", "EAP XP", "Bootable Jar", "UBI8"]
icon: /images/type-jboss.svg
